### ISSUE TITLE
Plots: funny .png graphs for CONSTR and some other variables  

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/rosstat-kep-data#78]
Must be one picture per png file

Example (wrong): ![](https://raw.githubusercontent.com/epogrebnyak/rosstat-kep-data/master/output/png/CONSTR_yoy.png)

**Comment by dniku** [comment]
This only happens when running `example_import.py` and not while running `plots.py` directly. For now, I've regenerated the images and pushed them into the repository.

It looks like the problem was introduced in https://github.com/epogrebnyak/rosstat-kep-data/commit/d72a1266a34e5beec64a3ac749570d3e4d5ffe93#diff-f95fdbd024eb803f79f0bb6f77e9b0fbL58 by commenting out `plt.close()`. Reverting that change fixes the problem. I assume it was done on purpose, so I'm not pushing a fix yet, until we find out why it was done.

**Comment by epogrebnyak** [comment]
I think something was tested, but now it is ok to uncomment.
